module.exports = {
 verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY",
 description: "Chizuru Mizuhara - Discord bot for Fun, Memes, Images, Giveaway, Economy, Anime and NSFW! Chizuru Mizuhara has 136 commands!",
 twitter: "@jingexz01",
 mobile: "false",
 image: "banner.jpg",
 server: "https://jingexz01.gq/discord-server",
 authorwebsite: "https://jingexz01.gq",
 status: "https://stats.uptimerobot.com/5lVA7t0zZq",
 author: "Jingexz01 (Jingexz01#2841)",
 ownerid: "708159504352673805",
 github: "Jingexz01",
 repo: "majobot",
 domain: process.env.DOMAIN,
 google_analitics: process.env.ANALYTICS,
 clientSecret: process.env.SECRET,
 id: process.env.ID,
 port: process.env.PORT,
 sessionSecret: process.env.SESSION_SECRET,
 prefix: process.env.PREFIX,
 scopes: "bot%20applications.commands",
 premissions: "8",
 youtube: process.env.YOUTUBE,
 dashboard: process.env.DASHBOARD,
 brainid: process.env.BRAINID,
 brainkey: process.env.BRAINKEY,
 cookies: process.env.COOKIES,
 statuschannel: "739683566455357483",
 suggestionschannel: "739683566455357483",
 newstitle: "<:tada:> Good news!",
 news: "Chizuru Mizuhara now has new commands. Check those commands above",
};
